[package]
name = "quicksort"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "quicksort_bench"
harness = false

[dependencies]
fastrand = "2.3.0"
bytemuck = "1.24.0"
