[package]
name = "map_reduce"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "map_reduce_bench"
harness = false

[[bench]]
name = "map_reduce_bench_rayon"
harness = false

[dependencies]
rayon = "1.11.0"
fastrand = "2.3.0"
